version: '3'
services:
  load_balancer1:
    build:
      context: ./nginx
    ports:
      - "8090:8080"
    depends_on:
      - registry
      - db
      - persistence
      - auth
      - image
      - recommender
      - webui
      - redis

  load_balancer2:
    build:
      context: ./nginx
    ports:
      - "8091:8080"
    depends_on:
      - registry
      - db
      - persistence
      - auth
      - image
      - recommender
      - webui
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"

  mysql:
    image: mysql:8.4
    ports:
      - "3307:3306"
    command: --mysql-native-password=ON --transaction-isolation=READ-COMMITTED
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fixed_window_counter_db
    volumes:
      - ./nginx/lua_scripts/mysql/init/init_fixed_window_counter.sql:/docker-entrypoint-initdb.d/init_fixed_window_counter.sql
      - ./nginx/lua_scripts/mysql/init/init_sliding_window_counter.sql:/docker-entrypoint-initdb.d/init_sliding_window_counter.sql
      - ./nginx/lua_scripts/mysql/init/init_sliding_window_logs.sql:/docker-entrypoint-initdb.d/init_sliding_window_logs.sql
      - ./nginx/lua_scripts/mysql/init/init_token_bucket.sql:/docker-entrypoint-initdb.d/init_token_bucket.sql
      - ./nginx/lua_scripts/mysql/init/init_leaky_bucket.sql:/docker-entrypoint-initdb.d/init_leaky_bucket.sql
      - ./nginx/lua_scripts/mysql/init/init_gcra.sql:/docker-entrypoint-initdb.d/init_gcra.sql

  registry:
    image: descartesresearch/teastore-registry
    expose:
      - "8080"
    ports:
      - "8083:8080"

  db:
    image: descartesresearch/teastore-db
    expose:
      - "3306"
    ports:
      - "3306:3306"

  persistence:
    image: descartesresearch/teastore-persistence
    expose:
      - "8080"
    ports:
      - "8084:8080"
    environment:
      HOST_NAME: "persistence"
      REGISTRY_HOST: "registry"
      DB_HOST: "db"
      DB_PORT: "3306"

  auth:
    image: descartesresearch/teastore-auth
    expose:
      - "8080"
    ports:
      - "8085:8080"
    environment:
      HOST_NAME: "auth"
      REGISTRY_HOST: "registry"

  image:
    image: descartesresearch/teastore-image
    expose:
      - "8080"
    ports:
      - "8086:8080"
    environment:
      HOST_NAME: "image"
      REGISTRY_HOST: "registry"

  recommender:
    image: descartesresearch/teastore-recommender
    expose:
      - "8080"
    ports:
      - "8087:8080"
    environment:
      HOST_NAME: "recommender"
      REGISTRY_HOST: "registry"

  webui:
    image: descartesresearch/teastore-webui
    expose:
      - "8080"
    ports:
      - "8080:8080"
    environment:
      HOST_NAME: "webui"
      REGISTRY_HOST: "registry"

networks:
  default:
    name: teastore-network
